const CONFIG = {
  LOCATIONS: [
    { name: "Sinza", count: 42 },
    { name: "Ubungo", count: 28 },
    { name: "Mbezi", count: 35 },
    { name: "Tegeta", count: 19 },
    { name: "Masaki", count: 15 },
    { name: "Upanga", count: 12 },
    { name: "Kariakoo", count: 56 },
    { name: "Kinondoni", count: 47 },
    { name: "Mwenge", count: 38 },
    { name: "Tabata", count: 24 },
    { name: "Ilala", count: 31 },
    { name: "Buguruni", count: 43 }
  ],
  PROPERTY_TYPES: [
    { id: "bedsitter", label: "Bedsitter", icon: "🛌" },
    { id: "single", label: "Single Room", icon: "🚪" },
    { id: "apartment", label: "Apartment", icon: "🏢" },
    { id: "studio", label: "Studio", icon: "🎨" },
    { id: "duplex", label: "Duplex", icon: "🏘️" },
    { id: "house", label: "House", icon: "🏠" },
    { id: "commercial", label: "Commercial", icon: "🏬" },
    { id: "land", label: "Land", icon: "📐" }
  ],
  AMENITIES: [
    { id: "water", label: "Maji 24/7", icon: "💧" },
    { id: "security", label: "Ulinzi 24/7", icon: "👮" },
    { id: "parking", label: "Parking", icon: "🚗" },
    { id: "wifi", label: "Wi-Fi High Speed", icon: "📶" },
    { id: "generator", label: "Jenereta", icon: "⚡" },
    { id: "furnished", label: "Samani Kamili", icon: "🛋️" },
    { id: "ac", label: "Air Conditioning", icon: "❄️" },
    { id: "pool", label: "Bwawa", icon: "🏊" },
    { id: "gym", label: "Gym", icon: "💪" },
    { id: "garden", label: "Bustani", icon: "🌳" },
    { id: "cctv", label: "CCTV", icon: "📹" },
    { id: "elevator", label: "Elevator", icon: "🔼" }
  ],
  PRICE_RANGES: [
    { label: "Chini ya TZS 100,000", min: 0, max: 100000 },
    { label: "TZS 100,000 - 300,000", min: 100000, max: 300000 },
    { label: "TZS 300,000 - 500,000", min: 300000, max: 500000 },
    { label: "TZS 500,000 - 1,000,000", min: 500000, max: 1000000 },
    { label: "Zaidi ya TZS 1,000,000", min: 1000000, max: 999999999 }
  ]
};

const translations = {
  sw: {
    appName: "HouseLink Tanzania",
    tagline: "Nyumba Bora, Makazi Bora",
    home: "Nyumbani",
    listings: "Nyumba",
    upload: "Weka Tangazo",
    favorites: "Vipendwa",
    login: "Ingia",
    logout: "Toka",
    signup: "Jisajili Sasa",
    darkMode: "Hali ya Giza",
    language: "Lugha",
    searchPlaceholder: "Tafuta nyumba, mtaa, au eneo...",
    filter: "Chuja",
    price: "Bei",
    location: "Eneo",
    type: "Aina",
    bedrooms: "Vyumba",
    bathrooms: "Bafu",
    contact: "Wasiliana",
    schedule: "Panga Uangalizi",
    message: "Tuma Ujumbe",
    edit: "Hariri",
    delete: "Futa",
    save: "Hifadhi",
    share: "Shiriki",
    broker: "Wakala",
    buyer: "Mnunuzi",
    tenant: "Mpangaji",
    role: "Chagua Jukumu",
    name: "Jina",
    email: "Barua Pepe",
    phone: "Namba ya Simu",
    password: "Nenosiri",
    confirmPassword: "Thibitisha Nenosiri",
    myListings: "Tangazo Zangu",
    myMessages: "Ujumbe Wangu",
    dashboard: "Dashibodi",
    welcome: "Karibu",
    featured: "Zilizoangaziwa",
    recent: "Hivi Karibuni",
    viewAll: "Angalia Zote",
    about: "Kuhusu Sisi",
    contactUs: "Wasiliana Nasi",
    services: "Huduma",
    blog: "Blog",
    testimonials: "Maoni ya Wateja",
    privacy: "Faragha",
    terms: "Masharti",
    copyright: "© 2024 HouseLink Tanzania. Haki zote zimehifadhiwa.",
    description: "Maelezo",
    amenities: "Vifaa",
    available: "Inapatikana",
    notAvailable: "Haipatikani",
    bookViewing: "Panga Uangalizi",
    sendMessage: "Tuma Ujumbe kwa Wakala",
    yourMessage: "Andika ujumbe wako hapa...",
    send: "Tuma",
    cancel: "Ghairi",
    confirmDelete: "Thibitisha Kufuta",
    deleteConfirm: "Una uhakika unataka kufuta tangazo hili?",
    yes: "Ndio",
    no: "Hapana",
    saved: "Imehifadhiwa",
    removed: "Imeondolewa",
    success: "Imefanikiwa",
    error: "Hitilafu",
    loading: "Inapakia...",
    dontHaveAccount: "Huna akaunti?",
    forgotPassword: "Umesahau nenosiri?",
    resetPassword: "Weka Upya Nenosiri",
    viewDetails: "Angalia Maelezo",
    applyNow: "Omba Sasa",
    bookNow: "Bokisha Sasa",
    search: "Tafuta",
    clearFilters: "Futa Vichujio",
    sortBy: "Panga Kwa",
    newest: "Mpya Zaidi",
    priceLowHigh: "Bei: Chini - Juu",
    priceHighLow: "Bei: Juu - Chini",
    featuredFirst: "Zilizoangaziwa Kwanza",
    mapView: "Angalia Ramani",
    listView: "Angalia Orodha",
    saveSearch: "Hifadhi Utafutaji",
    savedSearches: "Utafutaji Uliohifadhiwa",
    notifications: "Arifa",
    profile: "Wasifu",
    settings: "Mipangilio",
    help: "Usaidizi",
    faq: "Maswali Yanayoulizwa",
    howItWorks: "Inafanya Kazi Vipi?",
    forBrokers: "Kwa Wawakala",
    forOwners: "Kwa Wenyewe Nyumba",
    forTenants: "Kwa Wapangaji",
    mortgageCalc: "Kikokotoo cha Mikopo",
    areaGuide: "Mwongozo wa Maeneo",
    marketTrends: "Mienendo ya Soko",
    postAd: "Weka Tangazo",
    manageProperties: "Dhibiti Mali",
    analytics: "Takwimu",
    inbox: "Kikasha",
    compose: "Andika",
    markRead: "Weka Imesomwa",
    deleteAll: "Futa Zote",
    reply: "Jibu",
    forward: "Peleka",
    archive: "Hifadhi",
    spam: "Barua Taka",
    trustSafety: "Imara na Salama",
    verified: "Imethibitishwa",
    premium: "Premium",
    basic: "Msingi",
    upgrade: "Boresha",
    payment: "Malipo",
    invoice: "Anuarisha",
    receipt: "Risiti",
    download: "Pakua",
    print: "Print",
    export: "Toa Nje",
    import: "Ingiza",
    backup: "Salio",
    restore: "Rudisha",
    feedback: "Maoni",
    rate: "Kadiria",
    review: "Tathmini",
    report: "Ripoti",
    block: "Ziba",
    unblock: "Fungua",
    follow: "Fuata",
    unfollow: "Acha Kufuata",
    subscribe: "Jiandikishe",
    unsubscribe: "Jiondoe",
    trending: "Inavuma",
    popular: "Maarufu",
    recommended: "Ilipendekezwa",
    nearby: "Karibu",
    similar: "Kama Hii",
    compare: "Linganisha",
    shortlist: "Orodha Fupi",
    viewed: "Iliangaliwa",
    contacted: "Iliwasiliana",
    scheduled: "Iliopangwa",
    visited: "Iliotembelewa",
    applied: "Iliyoombwa",
    approved: "Imekubaliwa",
    rejected: "Imekataliwa",
    pending: "Inasubiri",
    completed: "Imekamilika",
    cancelled: "Imeshindwa",
    expired: "Imeisha",
    renewed: "Imerekebishwa",
    extended: "Imepanuliwa",
    terminated: "Imekatishwa",
    transferred: "Imehamishwa",
    sold: "Imeuzwa",
    rented: "Imechukuliwa",
    vacant: "Wazi",
    occupied: "Imezaliwa",
    underConstruction: "Inajengwa",
    readyToMove: "Tayari Kukaa",
    furnished: "Samani",
    semiFurnished: "Samani Kidogo",
    unfurnished: "Hakuna Samani",
    petFriendly: "Inakubali Wanyama",
    smokeFree: "Hakuna Sigara",
    wheelchair: "Inafaa Kwa Wenye Vitanda",
    gardenView: "Mtazamo wa Bustani",
    seaView: "Mtazamo wa Bahari",
    cityView: "Mtazamo wa Jiji",
    mountainView: "Mtazamo wa Mlima"
  },
  en: {
    appName: "HouseLink Tanzania",
    tagline: "Better Homes, Better Living",
    home: "Home",
    listings: "Properties",
    upload: "Post Listing",
    favorites: "Favorites",
    login: "Login",
    logout: "Logout",
    signup: "Sign Up Now",
    darkMode: "Dark Mode",
    language: "Language",
    searchPlaceholder: "Search properties, neighborhood, or area...",
    filter: "Filter",
    price: "Price",
    location: "Location",
    type: "Type",
    bedrooms: "Bedrooms",
    bathrooms: "Bathrooms",
    contact: "Contact",
    schedule: "Schedule Viewing",
    message: "Send Message",
    edit: "Edit",
    delete: "Delete",
    save: "Save",
    share: "Share",
    broker: "Broker",
    buyer: "Buyer",
    tenant: "Tenant",
    role: "Choose Role",
    name: "Name",
    email: "Email",
    phone: "Phone Number",
    password: "Password",
    confirmPassword: "Confirm Password",
    myListings: "My Listings",
    myMessages: "My Messages",
    dashboard: "Dashboard",
    welcome: "Welcome",
    featured: "Featured",
    recent: "Recent",
    viewAll: "View All",
    about: "About Us",
    contactUs: "Contact Us",
    services: "Services",
    blog: "Blog",
    testimonials: "Testimonials",
    privacy: "Privacy",
    terms: "Terms",
    copyright: "© 2024 HouseLink Tanzania. All rights reserved.",
    description: "Description",
    amenities: "Amenities",
    available: "Available",
    notAvailable: "Not Available",
    bookViewing: "Book Viewing",
    sendMessage: "Send Message to Broker",
    yourMessage: "Type your message here...",
    send: "Send",
    cancel: "Cancel",
    confirmDelete: "Confirm Delete",
    deleteConfirm: "Are you sure you want to delete this listing?",
    yes: "Yes",
    no: "No",
    saved: "Saved",
    removed: "Removed",
    success: "Success",
    error: "Error",
    loading: "Loading...",
    dontHaveAccount: "Don't have an account?",
    forgotPassword: "Forgot Password?",
    resetPassword: "Reset Password",
    viewDetails: "View Details",
    applyNow: "Apply Now",
    bookNow: "Book Now",
    search: "Search",
    clearFilters: "Clear Filters",
    sortBy: "Sort By",
    newest: "Newest",
    priceLowHigh: "Price: Low - High",
    priceHighLow: "Price: High - Low",
    featuredFirst: "Featured First",
    mapView: "Map View",
    listView: "List View",
    saveSearch: "Save Search",
    savedSearches: "Saved Searches",
    notifications: "Notifications",
    profile: "Profile",
    settings: "Settings",
    help: "Help",
    faq: "FAQ",
    howItWorks: "How It Works",
    forBrokers: "For Brokers",
    forOwners: "For Owners",
    forTenants: "For Tenants",
    mortgageCalc: "Mortgage Calculator",
    areaGuide: "Area Guide",
    marketTrends: "Market Trends",
    postAd: "Post Ad",
    manageProperties: "Manage Properties",
    analytics: "Analytics",
    inbox: "Inbox",
    compose: "Compose",
    markRead: "Mark as Read",
    deleteAll: "Delete All",
    reply: "Reply",
    forward: "Forward",
    archive: "Archive",
    spam: "Spam",
    trustSafety: "Trust & Safety",
    verified: "Verified",
    premium: "Premium",
    basic: "Basic",
    upgrade: "Upgrade",
    payment: "Payment",
    invoice: "Invoice",
    receipt: "Receipt",
    download: "Download",
    print: "Print",
    export: "Export",
    import: "Import",
    backup: "Backup",
    restore: "Restore",
    feedback: "Feedback",
    rate: "Rate",
    review: "Review",
    report: "Report",
    block: "Block",
    unblock: "Unblock",
    follow: "Follow",
    unfollow: "Unfollow",
    subscribe: "Subscribe",
    unsubscribe: "Unsubscribe",
    trending: "Trending",
    popular: "Popular",
    recommended: "Recommended",
    nearby: "Nearby",
    similar: "Similar",
    compare: "Compare",
    shortlist: "Shortlist",
    viewed: "Viewed",
    contacted: "Contacted",
    scheduled: "Scheduled",
    visited: "Visited",
    applied: "Applied",
    approved: "Approved",
    rejected: "Rejected",
    pending: "Pending",
    completed: "Completed",
    cancelled: "Cancelled",
    expired: "Expired",
    renewed: "Renewed",
    extended: "Extended",
    terminated: "Terminated",
    transferred: "Transferred",
    sold: "Sold",
    rented: "Rented",
    vacant: "Vacant",
    occupied: "Occupied",
    underConstruction: "Under Construction",
    readyToMove: "Ready to Move",
    furnished: "Furnished",
    semiFurnished: "Semi-Furnished",
    unfurnished: "Unfurnished",
    petFriendly: "Pet Friendly",
    smokeFree: "Smoke Free",
    wheelchair: "Wheelchair Accessible",
    gardenView: "Garden View",
    seaView: "Sea View",
    cityView: "City View",
    mountainView: "Mountain View"
  }
};
